server:
  port: 8080
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.serein.myblog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true